### ISSUE TITLE
Doesn't work for ESP-IDF 4.1

### ISSUE THREAD

**Issue by Oleg-Perevyshin** [BrianPugh/cookiecutter-esp32-webserver#4]
Hello!

I performed all the steps as described.
- Installed pip3 install cookiecutter
- cookiecutter -c 4.1-compat git@github.com:BrianPugh/cookiecutter-esp32-webserver.git

In terminal:
`
poe@MacBook-Pro-Oleg ~ % cookiecutter -c 4.1-compat git@github.com:BrianPugh/cookiecutter-esp32-webserver.git
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cookiecutter/main.py", line 67, in cookiecutter
    repo_dir, cleanup = determine_repo_dir(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cookiecutter/repository.py", line 110, in determine_repo_dir
    cloned_repo = clone(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cookiecutter/vcs.py", line 101, in clone
    subprocess.check_output(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', 'git@github.com:BrianPugh/cookiecutter-esp32-webserver.git']' returned non-zero exit status 128.
poe@MacBook-Pro-Oleg ~ % 
`
Help! What did I do wrong?

**Comment by BrianPugh** [comment]
That suggests some issue with your SSH keys. A more environement generic command would be:

```
cookiecutter -c 4.1-compat https://github.com/BrianPugh/cookiecutter-esp32-webserver.git
```

I'll probably update the readme to use this form instead of relying on SSH.

Let me know if this solves your issue.

**Comment by Oleg-Perevyshin** [comment]
I installed version 4.2
The errors were similar.
I changed the path through the https and everything worked correctly.
Thank you!

**Comment by BrianPugh** [comment]
updated readme to use https instead of ssh:

https://github.com/BrianPugh/cookiecutter-esp32-webserver/commit/e4b60265864e25a4618183171c897de01e385771
